import type { Product } from "./types";

/**
 * Seeded mock catalog — swap for real marketplace APIs later.
 * Exposed read-only to remote agents via WebMCP tool `catalog_list_seed` (see /api/mcp).
 */
export const MOCK_MACBOOK_M4_32GB_LISTINGS: Product[] = [
  {
    id: "amz-mbp-m4-32-1",
    title: "Apple MacBook Pro 14\" — M4, 32GB RAM, 512GB SSD (Latest)",
    marketplace: "Amazon",
    price: 1999,
    ramGb: 32,
    chip: "Apple M4",
    condition: "new",
    sellerName: "Amazon.com",
    sellerRating: 4.9,
    returnPolicy: "30-day free returns",
    shippingCost: 0,
    shippingDays: 2,
    couponEligible: true,
    listPrice: 1999,
    wasPrice: 2149,
    estimatedFinalPrice: 1999,
    trustScore: 96,
    recommendationReason: "Prime fulfillment, strong return policy, coupon-eligible.",
    warrantyMonths: 12,
  },
  {
    id: "bb-mbp-m4-32-1",
    title: "MacBook Pro 14\" Laptop — Apple M4 chip, 32GB, 512GB SSD",
    marketplace: "Best Buy",
    price: 1949,
    ramGb: 32,
    chip: "Apple M4",
    condition: "open_box",
    sellerName: "Best Buy — Store #442",
    sellerRating: 4.7,
    returnPolicy: "15-day return, restocking fee may apply on open-box",
    shippingCost: 0,
    shippingDays: 3,
    couponEligible: true,
    listPrice: 1949,
    estimatedFinalPrice: 1949,
    trustScore: 91,
    recommendationReason: "Open-box discount with national retailer backing.",
    warrantyMonths: 12,
  },
  {
    id: "wm-mbp-m4-32-1",
    title: "Apple MacBook Pro 14\" — M4, 32GB RAM, 512GB SSD",
    marketplace: "Walmart",
    price: 1939,
    ramGb: 32,
    chip: "Apple M4",
    condition: "new",
    sellerName: "Walmart.com — Sold & shipped by Walmart",
    sellerRating: 4.8,
    returnPolicy: "30-day returns (see Walmart policy)",
    shippingCost: 0,
    shippingDays: 4,
    couponEligible: true,
    listPrice: 1939,
    estimatedFinalPrice: 1939,
    trustScore: 90,
    recommendationReason: "Nationwide fulfillment; check rollbacks vs. street pricing.",
    warrantyMonths: 12,
  },
  {
    id: "tgt-mbp-m4-32-1",
    title: "Apple MacBook Pro 14\" — M4, 32GB RAM, 512GB SSD",
    marketplace: "Target",
    price: 1945,
    ramGb: 32,
    chip: "Apple M4",
    condition: "new",
    sellerName: "Target Plus — Shipped by Target",
    sellerRating: 4.85,
    returnPolicy: "30-day return (see Target electronics policy)",
    shippingCost: 0,
    shippingDays: 3,
    couponEligible: true,
    listPrice: 1945,
    estimatedFinalPrice: 1945,
    trustScore: 92,
    recommendationReason: "RedCard-eligible shipping; compare Circle offers at checkout.",
    warrantyMonths: 12,
  },
  {
    id: "costco-mbp-m4-32",
    title: "Apple MacBook Pro 14\" M4 / 32GB / 512GB — Member Deal",
    marketplace: "Costco",
    price: 1929,
    ramGb: 32,
    chip: "Apple M4",
    condition: "new",
    sellerName: "Costco Wholesale",
    sellerRating: 4.8,
    returnPolicy: "90-day electronics return (member)",
    shippingCost: 0,
    shippingDays: 5,
    couponEligible: false,
    listPrice: 1929,
    estimatedFinalPrice: 1929,
    trustScore: 94,
    recommendationReason: "Excellent return window; membership required at checkout.",
    warrantyMonths: 12,
  },
  {
    id: "ebay-m4-pro-32-main",
    title: "MacBook Pro 14 M4 — 32GB RAM — Space Black — Like New",
    marketplace: "eBay",
    price: 2165,
    ramGb: 32,
    chip: "Apple M4",
    condition: "refurbished",
    sellerName: "BayTech Deals (Top Rated Plus)",
    sellerRating: 4.95,
    returnPolicy: "30-day money-back guarantee",
    shippingCost: 38.75,
    shippingDays: 4,
    couponEligible: true,
    listPrice: 2165,
    wasPrice: 2499,
    estimatedFinalPrice: 2165 + 38.75,
    trustScore: 92,
    recommendationReason:
      "After SAVE15, lands near $1,879 all-in — best negotiation upside vs. comps.",
    warrantyMonths: 6,
  },
  {
    id: "bh-mbp-m4-32",
    title: "Apple 14\" MacBook Pro (M4, 32GB RAM, 512GB) Space Black",
    marketplace: "B&H",
    price: 1989,
    ramGb: 32,
    chip: "Apple M4",
    condition: "new",
    sellerName: "B&H Photo Video",
    sellerRating: 4.9,
    returnPolicy: "30-day return; unopened preferred",
    shippingCost: 0,
    shippingDays: 3,
    couponEligible: true,
    listPrice: 1989,
    estimatedFinalPrice: 1989,
    trustScore: 95,
    recommendationReason: "Trusted pro retailer, tax/shipping friendly in many states.",
    warrantyMonths: 12,
  },
  {
    id: "apple-refurb-m4-32",
    title: "14-inch MacBook Pro Apple M4 chip — 32GB — 512GB — Apple Certified",
    marketplace: "Apple Refurbished",
    price: 1799,
    ramGb: 32,
    chip: "Apple M4",
    condition: "refurbished",
    sellerName: "Apple Inc.",
    sellerRating: 5,
    returnPolicy: "14-day returns, AppleCare eligible",
    shippingCost: 0,
    shippingDays: 3,
    couponEligible: false,
    listPrice: 1799,
    estimatedFinalPrice: 1799,
    trustScore: 99,
    recommendationReason: "Lowest risk refurb path with factory warranty equivalent.",
    warrantyMonths: 12,
  },
  {
    id: "mc-mbp-m4-32",
    title: "Apple MacBook Pro 14\" M4 / 32GB / 512GB (In-Store Pickup)",
    marketplace: "Micro Center",
    price: 1899,
    ramGb: 32,
    chip: "Apple M4",
    condition: "new",
    sellerName: "Micro Center — Tustin",
    sellerRating: 4.6,
    returnPolicy: "30-day returns with original packaging",
    shippingCost: 19,
    shippingDays: 2,
    couponEligible: true,
    listPrice: 1899,
    estimatedFinalPrice: 1899 + 19,
    trustScore: 88,
    recommendationReason: "Strong in-person inspection option before pickup.",
    warrantyMonths: 12,
  },
  {
    id: "fb-mp-m4-32",
    title: "Macbook pro m4 32gb urgent sale !!!!",
    marketplace: "Facebook Marketplace",
    price: 1650,
    ramGb: 32,
    chip: "Apple M4",
    condition: "used",
    sellerName: "Local Seller — Cash/Venmo",
    sellerRating: 3.1,
    returnPolicy: "No formal returns — peer-to-peer",
    shippingCost: 0,
    shippingDays: 1,
    couponEligible: false,
    listPrice: 1650,
    wasPrice: 3999,
    estimatedFinalPrice: 1650,
    trustScore: 54,
    recommendationReason: "Lowest cash price but elevated scam risk — verify serial before paying.",
    warrantyMonths: 0,
  },
];

/** Non-Mac demos so arbitrary prompts can surface plausible rows without live search. */
export const MOCK_GENERAL_LISTINGS: Product[] = [
  {
    id: "amz-xm5",
    title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones — Black",
    marketplace: "Amazon",
    price: 328,
    ramGb: 0,
    chip: "—",
    condition: "new",
    sellerName: "Amazon.com",
    sellerRating: 4.8,
    returnPolicy: "30-day free returns",
    shippingCost: 0,
    shippingDays: 2,
    couponEligible: true,
    listPrice: 399,
    wasPrice: 399,
    estimatedFinalPrice: 328,
    trustScore: 96,
    recommendationReason: "Strong street pricing vs. list; watch for renewed SKUs.",
    warrantyMonths: 12,
  },
  {
    id: "bb-iphone15",
    title: "Apple iPhone 15 Pro 256GB — Natural Titanium (Unlocked)",
    marketplace: "Best Buy",
    price: 999,
    ramGb: 8,
    chip: "A17 Pro",
    condition: "new",
    sellerName: "Best Buy",
    sellerRating: 4.7,
    returnPolicy: "14–15 day return window",
    shippingCost: 0,
    shippingDays: 3,
    couponEligible: false,
    listPrice: 1099,
    estimatedFinalPrice: 999,
    trustScore: 92,
    recommendationReason: "Carrier-free unlocked units often negotiable in open-box.",
    warrantyMonths: 12,
  },
  {
    id: "wm-oled",
    title: "LG 48\" OLED evo C4 Series 4K Smart TV — Alexa Built-In",
    marketplace: "Walmart",
    price: 1096,
    ramGb: 0,
    chip: "—",
    condition: "new",
    sellerName: "Walmart.com",
    sellerRating: 4.6,
    returnPolicy: "30-day electronics return",
    shippingCost: 0,
    shippingDays: 5,
    couponEligible: true,
    listPrice: 1299,
    wasPrice: 1299,
    estimatedFinalPrice: 1096,
    trustScore: 90,
    recommendationReason: "Panel deals move weekly — compare warehouse clubs.",
    warrantyMonths: 12,
  },
  {
    id: "bh-dell-monitor",
    title: "Dell UltraSharp U2723QE 27\" 4K USB-C Hub Monitor",
    marketplace: "B&H",
    price: 579,
    ramGb: 0,
    chip: "—",
    condition: "new",
    sellerName: "B&H Photo Video",
    sellerRating: 4.9,
    returnPolicy: "30-day return",
    shippingCost: 0,
    shippingDays: 3,
    couponEligible: true,
    listPrice: 629,
    estimatedFinalPrice: 579,
    trustScore: 95,
    recommendationReason: "Dock-friendly 4K for hybrid work setups.",
    warrantyMonths: 36,
  },
  {
    id: "ebay-framework",
    title: "Framework Laptop 13 — AMD Ryzen 7 — 32GB RAM — DIY Edition",
    marketplace: "eBay",
    price: 1249,
    ramGb: 32,
    chip: "AMD Ryzen 7",
    condition: "refurbished",
    sellerName: "Circular Tech (Top Rated)",
    sellerRating: 4.9,
    returnPolicy: "30-day returns",
    shippingCost: 22,
    shippingDays: 4,
    couponEligible: false,
    listPrice: 1399,
    estimatedFinalPrice: 1271,
    trustScore: 89,
    recommendationReason: "Repairable laptop — good negotiation margin vs. new MSRP.",
    warrantyMonths: 6,
  },
  {
    id: "costco-dyson",
    title: "Dyson V15 Detect Cordless Vacuum — Member Exclusive",
    marketplace: "Costco",
    price: 649,
    ramGb: 0,
    chip: "—",
    condition: "new",
    sellerName: "Costco Wholesale",
    sellerRating: 4.7,
    returnPolicy: "90-day electronics return",
    shippingCost: 0,
    shippingDays: 5,
    couponEligible: false,
    listPrice: 749,
    estimatedFinalPrice: 649,
    trustScore: 94,
    recommendationReason: "Bundled accessories common in warehouse kits.",
    warrantyMonths: 24,
  },
];

export const MOCK_CATALOG_ALL: Product[] = [
  ...MOCK_MACBOOK_M4_32GB_LISTINGS,
  ...MOCK_GENERAL_LISTINGS,
];
